"""Knowledge graph schema and utilities."""

from .schema import (
    EvidenceRef,
    NodeType,
    EdgeType,
    NODE_TIER,
    EDGE_TIER_1,
    SPINE_PARENT,
    NODE_DEPTH,
    MAX_SPINE_DEPTH,
    LEGACY_NODE_TYPES,
    LEGACY_EDGE_TYPES,
    canonical_node_type,
    canonical_edge_type,
    Chunk,
    Node,
    Edge,
    ExtractedNode,
    ExtractedEdge,
    ExtractionResult,
    slugify,
    dedup_evidence,
)

__all__ = [
    "EvidenceRef",
    "NodeType",
    "EdgeType",
    "NODE_TIER",
    "EDGE_TIER_1",
    "SPINE_PARENT",
    "NODE_DEPTH",
    "MAX_SPINE_DEPTH",
    "LEGACY_NODE_TYPES",
    "LEGACY_EDGE_TYPES",
    "canonical_node_type",
    "canonical_edge_type",
    "Chunk",
    "Node",
    "Edge",
    "ExtractedNode",
    "ExtractedEdge",
    "ExtractionResult",
    "slugify",
    "dedup_evidence",
]
